#! /bin/sh

killall -q sxhkd

sxhkd &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

nitrogen --restore &

killall -q nm-applet

nm-applet &

killall -q redshift
killall -q redshift-gtk

redshift-gtk &

killall -q polybar

polybar mybar &

killall -q dunst

dunst &

killall -q picom

picom &

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp state=floating
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Klavaro state=floating
bspc rule -a zoom desktop='^2'
bspc rule -a Thunar state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Arandr state=floating
bspc rule -a Lxappearance state=floating

wmname LG3D
