#!/usr/bin/bash

target="0"
if ! tmux has-session -t $target 2> /dev/null; then
    tmux neww
fi

tmux send-keys -t $target "sbatch /home/endim/scripts/run.sh" Enter
# tmux send-keys -t $target "sbatch /home/endim/pardnn/test/run.sh" Enter
# tmux send-keys -t $target "make" Enter
# tmux send-keys -t $target "python3 parse.py" Enter
# tmux send-keys -t $target "!!" Enter
